-- Bram Swinnen, "Strength Training for Soccer" (Routledge, 2016) kitabındaki
-- isimli hareketler genel hareket kütüphanesine ekleniyor. Bu bir referans
-- kütüphanesidir; belirli bir kartın (Üst Vücut/Alt Vücut) günlük programı
-- değildir — kart programları antrenman kartı ekranından, oyuncu/kart bazında
-- elle seçilip set/tekrar/ağırlık girilerek oluşturulur.

insert into public.exercises (name, category)
select x.name, x.category
from (values
  -- Core (Bölüm 5)
  ('Plank', 'strength'),
  ('Stability Ball Plank', 'strength'),
  ('Plank with Leg Lift', 'strength'),
  ('Plank with Arm Lift', 'strength'),
  ('Plank with Opposite Arm and Leg Lift', 'strength'),
  ('Stability Ball Knee Tuck', 'strength'),
  ('TRX Pike', 'strength'),
  ('Stability Ball Rollout', 'strength'),
  ('Kneeling Straight-Arm Stability Ball Rollout', 'strength'),
  ('Kneeling Ab Rollout', 'strength'),
  ('Straight-Arm Stability Ball Rollout', 'strength'),
  ('Hanging Knee Raise', 'strength'),
  ('Hanging Oblique-Knee Raise', 'strength'),
  ('Hanging Straight-Leg Raise', 'strength'),
  ('Barbell Torque', 'strength'),
  ('Horizontal Wood Chop', 'strength'),
  ('Vertiball Slam', 'strength'),
  ('Side Bridge', 'strength'),
  ('Oblique Bridge', 'strength'),
  ('Side Bridge with Abduction', 'strength'),
  ('3D Side Bridge', 'strength'),
  ('Split Stance Core Press', 'strength'),

  -- Two-leg knee dominant (Bölüm 6)
  ('Back Squat', 'strength'),
  ('Front Squat', 'strength'),
  ('Overhead Squat', 'strength'),
  ('Jump Squat', 'strength'),

  -- Single-leg knee dominant (Bölüm 7)
  ('Forward Step-Up', 'strength'),
  ('Lateral Step-Up', 'strength'),
  ('Crossover and Lateral Step-Up', 'strength'),
  ('Forward Lunge', 'strength'),
  ('Lateral Lunge', 'strength'),
  ('Resisted Lunge', 'strength'),
  ('Walking Lunge', 'strength'),
  ('Three-Spot Lunge', 'strength'),
  ('Split Squat', 'strength'),
  ('Bulgarian Split Squat', 'strength'),
  ('Single-Leg Squat', 'strength'),
  ('Single-Leg Box Squat', 'strength'),
  ('Resisted Slide-Board Back Lunge', 'strength'),
  ('Front Pull', 'strength'),
  ('Single-Leg Squat and Reach', 'strength'),
  ('Single-Leg Squat and Reach Around the Clock', 'strength'),
  ('Bulgarian Split Deadlift', 'strength'),
  ('Slide-Board Lateral Slide', 'strength'),
  ('Slide-Board Lateral Lunge', 'strength'),

  -- Hip dominant (Bölüm 8)
  ('Romanian Deadlift', 'strength'),
  ('Single-Leg Romanian Deadlift', 'strength'),
  ('Nordic Hamstring Exercise', 'strength'),
  ('Assisted Nordic Hamstring Exercise', 'strength'),
  ('Back Extension', 'strength'),
  ('Single-Leg Back Extension', 'strength'),
  ('Hamstring Combination', 'strength'),
  ('Single-Leg Hamstring Combination', 'strength'),

  -- Upper body press (Bölüm 9)
  ('Bench Press (Barbell)', 'strength'),
  ('Bench Press (Dumbbells)', 'strength'),
  ('Push-Up', 'strength'),
  ('Weight Plate Push-Up', 'strength'),
  ('Medicine Ball Push-Up on Two Balls', 'strength'),
  ('Medicine Ball Push-Up on One Ball', 'strength'),
  ('Medicine Ball Crossover Push-Up', 'strength'),
  ('Slide-Board Front Lever Push-Up', 'strength'),
  ('Clapping Push-Up', 'strength'),
  ('Depth-Jump Push-Up', 'strength'),
  ('Staggered-Stance, One-Arm Cable Press', 'strength'),
  ('Overhead Press', 'strength'),

  -- Upper body pull (Bölüm 10)
  ('Pull-Up', 'strength'),
  ('One-Arm Dumbbell Row', 'strength'),
  ('Inverse Row', 'strength'),
  ('Plyometric Inverse Row', 'strength'),
  ('Barbell Row', 'strength'),
  ('Staggered-Stance One-Arm Row', 'strength'),

  -- Hybrid (Bölüm 11)
  ('Battling Ropes Waves', 'strength'),
  ('Single-Leg Squat and Row', 'strength'),
  ('Back Lunge and One-Arm Press', 'strength'),
  ('Single-Leg Romanian Deadlift and Row', 'strength'),
  ('Push-Pull Combination', 'strength'),
  ('Squat and Press', 'strength'),

  -- Plyometrics (Bölüm 14)
  ('Box Jump', 'strength'),
  ('Hurdle Jump', 'strength'),
  ('Lateral Hurdle Jump', 'strength'),
  ('Step-Up Jump', 'strength'),
  ('Bulgarian Split Squat Jump', 'strength'),
  ('Side-to-Side Box Jump', 'strength'),
  ('Lateral Cone Hops', 'strength'),

  -- Olympic lifts (Bölüm 15)
  ('Clean Progression', 'strength'),
  ('Squat Clean', 'strength'),
  ('Snatch Progression', 'strength'),
  ('Squat Snatch', 'strength'),
  ('Alternating Split Jerk', 'strength')
) as x(name, category)
where not exists (select 1 from public.exercises e where e.name = x.name);

-- Kas grubu eşlemeleri (birincil = true, ikincil = false)
insert into public.exercise_muscle_groups (exercise_id, muscle_group_id, is_primary)
select e.id, mg.id, x.is_primary
from (values
  ('Plank', 'core', true),
  ('Stability Ball Plank', 'core', true),
  ('Plank with Leg Lift', 'core', true),
  ('Plank with Leg Lift', 'hip_flexors', false),
  ('Plank with Arm Lift', 'core', true),
  ('Plank with Arm Lift', 'shoulders', false),
  ('Plank with Opposite Arm and Leg Lift', 'core', true),
  ('Stability Ball Knee Tuck', 'core', true),
  ('Stability Ball Knee Tuck', 'hip_flexors', false),
  ('TRX Pike', 'core', true),
  ('TRX Pike', 'shoulders', false),
  ('Stability Ball Rollout', 'core', true),
  ('Kneeling Straight-Arm Stability Ball Rollout', 'core', true),
  ('Kneeling Ab Rollout', 'core', true),
  ('Straight-Arm Stability Ball Rollout', 'core', true),
  ('Hanging Knee Raise', 'core', true),
  ('Hanging Knee Raise', 'hip_flexors', false),
  ('Hanging Oblique-Knee Raise', 'core', true),
  ('Hanging Straight-Leg Raise', 'core', true),
  ('Hanging Straight-Leg Raise', 'hip_flexors', false),
  ('Barbell Torque', 'core', true),
  ('Horizontal Wood Chop', 'core', true),
  ('Vertiball Slam', 'core', true),
  ('Vertiball Slam', 'shoulders', false),
  ('Side Bridge', 'core', true),
  ('Oblique Bridge', 'core', true),
  ('Side Bridge with Abduction', 'core', true),
  ('Side Bridge with Abduction', 'hip_abductors', false),
  ('3D Side Bridge', 'core', true),
  ('Split Stance Core Press', 'core', true),
  ('Split Stance Core Press', 'shoulders', false),

  ('Back Squat', 'quadriceps', true),
  ('Back Squat', 'glutes', false),
  ('Front Squat', 'quadriceps', true),
  ('Front Squat', 'glutes', false),
  ('Overhead Squat', 'quadriceps', true),
  ('Overhead Squat', 'shoulders', false),
  ('Jump Squat', 'quadriceps', true),
  ('Jump Squat', 'glutes', false),

  ('Forward Step-Up', 'quadriceps', true),
  ('Forward Step-Up', 'glutes', false),
  ('Lateral Step-Up', 'quadriceps', true),
  ('Lateral Step-Up', 'hip_abductors', false),
  ('Crossover and Lateral Step-Up', 'quadriceps', true),
  ('Crossover and Lateral Step-Up', 'hip_abductors', false),
  ('Forward Lunge', 'quadriceps', true),
  ('Forward Lunge', 'glutes', false),
  ('Lateral Lunge', 'hip_adductors', true),
  ('Lateral Lunge', 'quadriceps', false),
  ('Resisted Lunge', 'quadriceps', true),
  ('Resisted Lunge', 'glutes', false),
  ('Walking Lunge', 'quadriceps', true),
  ('Walking Lunge', 'glutes', false),
  ('Three-Spot Lunge', 'quadriceps', true),
  ('Three-Spot Lunge', 'glutes', false),
  ('Split Squat', 'quadriceps', true),
  ('Split Squat', 'glutes', false),
  ('Bulgarian Split Squat', 'quadriceps', true),
  ('Bulgarian Split Squat', 'glutes', false),
  ('Single-Leg Squat', 'quadriceps', true),
  ('Single-Leg Squat', 'glutes', false),
  ('Single-Leg Box Squat', 'quadriceps', true),
  ('Single-Leg Box Squat', 'glutes', false),
  ('Resisted Slide-Board Back Lunge', 'quadriceps', true),
  ('Resisted Slide-Board Back Lunge', 'glutes', false),
  ('Front Pull', 'quadriceps', true),
  ('Front Pull', 'hip_adductors', false),
  ('Single-Leg Squat and Reach', 'quadriceps', true),
  ('Single-Leg Squat and Reach', 'glutes', false),
  ('Single-Leg Squat and Reach Around the Clock', 'quadriceps', true),
  ('Single-Leg Squat and Reach Around the Clock', 'glutes', false),
  ('Bulgarian Split Deadlift', 'hamstrings', true),
  ('Bulgarian Split Deadlift', 'glutes', false),
  ('Slide-Board Lateral Slide', 'hip_adductors', true),
  ('Slide-Board Lateral Slide', 'hip_abductors', false),
  ('Slide-Board Lateral Lunge', 'hip_adductors', true),
  ('Slide-Board Lateral Lunge', 'quadriceps', false),

  ('Romanian Deadlift', 'hamstrings', true),
  ('Romanian Deadlift', 'glutes', false),
  ('Single-Leg Romanian Deadlift', 'hamstrings', true),
  ('Single-Leg Romanian Deadlift', 'glutes', false),
  ('Nordic Hamstring Exercise', 'hamstrings', true),
  ('Assisted Nordic Hamstring Exercise', 'hamstrings', true),
  ('Back Extension', 'lower_back', true),
  ('Back Extension', 'glutes', false),
  ('Single-Leg Back Extension', 'lower_back', true),
  ('Single-Leg Back Extension', 'glutes', false),
  ('Hamstring Combination', 'hamstrings', true),
  ('Hamstring Combination', 'glutes', false),
  ('Single-Leg Hamstring Combination', 'hamstrings', true),
  ('Single-Leg Hamstring Combination', 'glutes', false),

  ('Bench Press (Barbell)', 'chest', true),
  ('Bench Press (Barbell)', 'triceps', false),
  ('Bench Press (Dumbbells)', 'chest', true),
  ('Bench Press (Dumbbells)', 'triceps', false),
  ('Push-Up', 'chest', true),
  ('Push-Up', 'triceps', false),
  ('Weight Plate Push-Up', 'chest', true),
  ('Weight Plate Push-Up', 'triceps', false),
  ('Medicine Ball Push-Up on Two Balls', 'chest', true),
  ('Medicine Ball Push-Up on Two Balls', 'core', false),
  ('Medicine Ball Push-Up on One Ball', 'chest', true),
  ('Medicine Ball Push-Up on One Ball', 'core', false),
  ('Medicine Ball Crossover Push-Up', 'chest', true),
  ('Medicine Ball Crossover Push-Up', 'core', false),
  ('Slide-Board Front Lever Push-Up', 'chest', true),
  ('Slide-Board Front Lever Push-Up', 'core', false),
  ('Clapping Push-Up', 'chest', true),
  ('Clapping Push-Up', 'triceps', false),
  ('Depth-Jump Push-Up', 'chest', true),
  ('Depth-Jump Push-Up', 'triceps', false),
  ('Staggered-Stance, One-Arm Cable Press', 'chest', true),
  ('Staggered-Stance, One-Arm Cable Press', 'core', false),
  ('Overhead Press', 'shoulders', true),
  ('Overhead Press', 'triceps', false),

  ('Pull-Up', 'upper_back', true),
  ('Pull-Up', 'biceps', false),
  ('One-Arm Dumbbell Row', 'upper_back', true),
  ('One-Arm Dumbbell Row', 'biceps', false),
  ('Inverse Row', 'upper_back', true),
  ('Inverse Row', 'biceps', false),
  ('Plyometric Inverse Row', 'upper_back', true),
  ('Plyometric Inverse Row', 'biceps', false),
  ('Barbell Row', 'upper_back', true),
  ('Barbell Row', 'biceps', false),
  ('Staggered-Stance One-Arm Row', 'upper_back', true),
  ('Staggered-Stance One-Arm Row', 'biceps', false),

  ('Battling Ropes Waves', 'shoulders', true),
  ('Battling Ropes Waves', 'core', false),
  ('Single-Leg Squat and Row', 'quadriceps', true),
  ('Single-Leg Squat and Row', 'upper_back', false),
  ('Back Lunge and One-Arm Press', 'quadriceps', true),
  ('Back Lunge and One-Arm Press', 'shoulders', false),
  ('Single-Leg Romanian Deadlift and Row', 'hamstrings', true),
  ('Single-Leg Romanian Deadlift and Row', 'upper_back', false),
  ('Push-Pull Combination', 'chest', true),
  ('Push-Pull Combination', 'upper_back', false),
  ('Squat and Press', 'quadriceps', true),
  ('Squat and Press', 'shoulders', false),

  ('Box Jump', 'quadriceps', true),
  ('Box Jump', 'glutes', false),
  ('Hurdle Jump', 'quadriceps', true),
  ('Hurdle Jump', 'glutes', false),
  ('Lateral Hurdle Jump', 'quadriceps', true),
  ('Lateral Hurdle Jump', 'hip_abductors', false),
  ('Step-Up Jump', 'quadriceps', true),
  ('Step-Up Jump', 'glutes', false),
  ('Bulgarian Split Squat Jump', 'quadriceps', true),
  ('Bulgarian Split Squat Jump', 'glutes', false),
  ('Side-to-Side Box Jump', 'quadriceps', true),
  ('Side-to-Side Box Jump', 'hip_abductors', false),
  ('Lateral Cone Hops', 'quadriceps', true),
  ('Lateral Cone Hops', 'hip_abductors', false),

  ('Clean Progression', 'quadriceps', true),
  ('Clean Progression', 'upper_back', false),
  ('Squat Clean', 'quadriceps', true),
  ('Squat Clean', 'shoulders', false),
  ('Snatch Progression', 'upper_back', true),
  ('Snatch Progression', 'shoulders', false),
  ('Squat Snatch', 'quadriceps', true),
  ('Squat Snatch', 'shoulders', false),
  ('Alternating Split Jerk', 'quadriceps', true),
  ('Alternating Split Jerk', 'shoulders', false)
) as x(exercise_name, muscle_group_name, is_primary)
join public.exercises e on e.name = x.exercise_name
join public.muscle_groups mg on mg.name = x.muscle_group_name
on conflict (exercise_id, muscle_group_id) do nothing;
